name: terminal_sparkline
description: Generate sparklines for your shell.
version: 1.0.0
homepage: https://github.com/dart-packages/terminal-sparkline

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.0
